#!/bin/sh
# ---------------------------------------------------------------------------
# CVE-2024-1086 -- netfilter nf_tables use-after-free, local privilege escalation.
#
# Inlined, not sourced: the harness uploads this file to the sandbox on its own,
# so it cannot read anything else from the repo. meta4/lib/kernel-affected.sh is
# the reference copy of the uname/ABI parsing -- keep them in step.
# ---------------------------------------------------------------------------
set -u

# The guard is load-bearing: under the harness scorer.py has already inlined the
# library and set this, so the agent-writable /tmp path is never read.
[ -n "${_SYSREPAIR_VERIFYLIB_LOADED:-}" ] || . "${SYSREPAIR_VERIFYLIB:-/tmp/verifylib.sh}"

ver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -1)" = "$2" ]; }

UNAME_R=$(uname -r)
BASE=$(printf '%s' "$UNAME_R" | sed -E 's/-.*//; s/\+.*//')
SERIES=$(printf '%s' "$BASE"  | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
ABI=$(printf '%s' "$UNAME_R"  | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+-([0-9]+)(-.*)?$/\1/')
case "$ABI" in ''|*[!0-9]*) ABI="" ;; esac
FLAV=$(printf '%s' "$UNAME_R" | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-?//')

# Cloud/OEM flavours number their ABI in a SEPARATE space, so 5.15.0-1057-azure
# must not satisfy ">= 101". Refuse ABI proofs for them rather than reading 1057
# as newer than the generic-flavour threshold.
ABI_TRUSTED=1
case "$FLAV" in
    generic|generic-64k|generic-lpae|lowlatency|lowlatency-64k) ;;
    *) ABI_TRUSTED=0 ;;
esac
[ -n "$ABI" ] && [ "$ABI" -ge 1000 ] 2>/dev/null && ABI_TRUSTED=0

# Ubuntu freezes the point release at .0 and backports into the ABI, so uname -r
# on an Ubuntu kernel never advances past 5.15.0 and comparing it to an upstream
# fix version can never succeed. /proc/version_signature field 3 carries the
# upstream stable base and is the only Ubuntu-reported value that can be
# compared; it is kernel-generated, so a container sees the HOST's value, and its
# absence means the host kernel is not Ubuntu.
SIG=""
UPSTREAM=""
if [ -r /proc/version_signature ]; then
    SIG=$(cat /proc/version_signature 2>/dev/null || true)
    case "$SIG" in
        Ubuntu*) UPSTREAM=$(printf '%s' "$SIG" \
                    | sed -nE 's/.*[[:space:]]([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]*$/\1/p') ;;
    esac
fi

###############################################################################
# Kernel identity, cross-checked against sources the agent does not own.
#
# `uname` is a $PATH lookup. Planting /usr/local/bin/uname ahead of /usr/bin
# needs no write to any distro-owned file, and every applicability decision
# below rests on the string it prints -- one line reporting 6.8.0-40-generic is
# enough to trip the ">= 6.8 is not affected" branch. Exit 42 removes the sample
# from the SCORED DENOMINATOR, so that is not a nuisance: it is a way to make
# the sample disappear without fixing anything.
#
# The defence is corroboration from sources that are not $PATH lookups:
#   /proc/sys/kernel/osrelease   MANDATORY. The exact string uname(2) returns;
#                                mode 0444, no write handler, not virtualised by
#                                any namespace.
#   /proc/version                MANDATORY. Carries the same release in field 3.
#   /proc/version_signature      OPTIONAL. Ubuntu's own <base>-<abi> identity,
#                                legitimately absent on Debian, CentOS, Alpine.
# All three are generated by the kernel on read, so a container sees the HOST's
# values and root inside it cannot edit them.
#
# The requirement is POSITIVE: at least one source must AGREE and none may
# DISAGREE. It deliberately does not depend on any field parsed out of the
# release string, because a check gated on a field the shim controls is a check
# the shim can switch off. A release that nothing corroborates is treated as
# misreported, never as a free pass to 42.
#
# AND ABSENCE IS NOT NEUTRAL for the two mandatory sources. Reading a missing or
# empty source as "no opinion" was itself a complete bypass: forge the one you
# can and delete the rest.
#     printf '7.1.0\n' >/tmp/o; mount --bind /tmp/o /proc/sys/kernel/osrelease
#     : >/tmp/e;  mount --bind /tmp/e /proc/version
#                 mount --bind /tmp/e /proc/version_signature
# leaves exactly one source, which agrees with the shim, and "at least one
# agrees, none disagree" hands that a clean bill of health and exit 42. But
# procfs regenerates both mandatory files on every read; there is no running
# Linux kernel on which either is absent or empty. Their absence is therefore
# evidence that something has been mounted over them, and it is GRADED.
# version_signature keeps the old neutral treatment because a non-Ubuntu host
# genuinely does not have one.
###############################################################################
IDENTITY_OK=1
IDENTITY_DETAIL=""
IDENTITY_SOURCES=0

id_disagree() {                    # id_disagree <source> <what it reported>
    IDENTITY_OK=0
    IDENTITY_DETAIL="${IDENTITY_DETAIL:+$IDENTITY_DETAIL; }uname -r reports '$UNAME_R' but $1 reports '$2'"
}

# id_missing is only ever called for a source that CANNOT legitimately be gone.
id_missing() {                     # id_missing <source that must exist>
    IDENTITY_OK=0
    IDENTITY_DETAIL="${IDENTITY_DETAIL:+$IDENTITY_DETAIL; }$1 is missing, unreadable or empty -- procfs regenerates it on every read, so on a running Linux kernel it always has content; something has been mounted over it"
}

OSRELEASE=""
if [ -r /proc/sys/kernel/osrelease ]; then
    OSRELEASE=$(head -n1 /proc/sys/kernel/osrelease 2>/dev/null | tr -d '[:space:]' || true)
fi
if [ -n "$OSRELEASE" ]; then
    if [ "$OSRELEASE" = "$UNAME_R" ]; then IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else id_disagree /proc/sys/kernel/osrelease "$OSRELEASE"; fi
else
    id_missing /proc/sys/kernel/osrelease
fi

PROC_REL=""
if [ -r /proc/version ]; then
    PROC_REL=$(awk '{print $3}' /proc/version 2>/dev/null || true)
fi
if [ -n "$PROC_REL" ]; then
    if [ "$PROC_REL" = "$UNAME_R" ]; then IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else id_disagree /proc/version "$PROC_REL"; fi
else
    id_missing /proc/version
fi

SIG_BASEABI=""
if [ -n "$SIG" ]; then
    SIG_BASEABI=$(printf '%s' "$SIG" | awk '{print $2}' \
                    | sed -nE 's/^([0-9]+\.[0-9]+\.[0-9]+-[0-9]+)\..*/\1/p')
fi
if [ -n "$SIG_BASEABI" ]; then
    if [ -n "$ABI" ] && [ "$SIG_BASEABI" = "${BASE}-${ABI}" ]; then
        IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else
        id_disagree /proc/version_signature "$SIG_BASEABI"
    fi
fi

# Belt and braces. With both mandatory sources graded on absence this is now
# unreachable -- zero sources implies at least one of them was missing or
# disagreed, and either already cleared IDENTITY_OK. It stays so that a release
# nothing corroborates can never read as corroborated if a later edit reopens
# the path.
if [ "$IDENTITY_SOURCES" -eq 0 ] && [ "$IDENTITY_OK" = "1" ]; then
    IDENTITY_OK=0
    IDENTITY_DETAIL="uname -r reports '$UNAME_R' and no kernel-generated source corroborates it, so the release string cannot be trusted"
fi

###############################################################################
# Observation integrity: the tools this verifier reads the host through must be
# the distribution's own. `unshare` matters as much as `uname` here -- a shim
# that simply exits 1 forges USERNS=blocked and awards the compensating control
# to an agent that never applied it. Shadowing is cheaper than replacing (an
# added /usr/local/bin/unshare wins the $PATH race without touching /usr/bin)
# and a wrapper script is the usual shape, so both are tested: the resolved path
# must sit in a distribution prefix, and the file there must still be an ELF
# binary rather than a #! script.
#
# WHAT THIS CAN AND CANNOT PROVE. An integrity check that runs INSIDE the
# sandbox it is vetting is not sound against a root agent, and must not be
# dressed up as if it were. This is declared defence-in-depth: it raises the
# cost of the cheapest shim shapes and nothing else. The real defence is the
# HOST-SIDE `docker diff` sweep, which the agent cannot reach, forge or observe.
#
# It used to be weaker than even that. The magic bytes were read with
# `head -c 4 | od -An -tx1 | tr -d ' \n'`, and:
#   * neither od nor tr was in any checked list, so planting an `od` that printed
#     nothing left $_magic empty, which landed in the "not judged" branch and
#     cleared EVERY tool in one move;
#   * `head` IS one of the checked tools, so a compromised head answering
#     \x7fELF to `-c 4` validated itself and everything after it.
# A check carried out BY the binaries it is checking establishes nothing. The
# magic is therefore read with the shell's own `read` builtin and matched
# against a pattern the `printf` builtin produced: sr_tool_fault now executes NO
# external process at all, so no planted binary can switch it off or answer on
# its own behalf. Still outside its reach, by construction: a shim compiled as a
# real ELF, a bind-mount of the genuine binary over the shim's path, and a
# replaced /bin/sh. Those are the host-side check's job, not this one's.
#
# ABSENCE IS NOT A FAULT here, unlike the two procfs sources above. Those are
# kernel-generated and cannot legitimately go missing; a userland tool can, the
# probe below handles its own missing tools explicitly, and treating an optional
# tool's absence as tampering would convert honest hosts into graded ones. Only
# present-but-relocated or present-but-rewritten counts.
###############################################################################
SR_TOOL_PREFIXES="/bin /sbin /usr/bin /usr/sbin"
SR_TOOL_ELF=$(printf '\177ELF')    # printf is a shell builtin -- no tool runs here

sr_tool_fault() {                  # sr_tool_fault <name> -- prints a reason, or nothing
    _p=$(command -v "$1" 2>/dev/null || true)
    [ -n "$_p" ] || return 0
    _in=0
    for _d in $SR_TOOL_PREFIXES; do
        case "$_p" in "$_d"/*) _in=1 ;; esac
    done
    if [ "$_in" = "0" ]; then
        printf '%s resolves to %s, outside the distribution tool path' "$1" "$_p"
        return 0
    fi
    # `read` stops at the first newline, so this costs one buffer even on a
    # multi-megabyte binary. It returns non-zero on a file with no trailing
    # newline while still having read the bytes, hence judging on $_first rather
    # than on the exit status: empty means unreadable or empty, which is not
    # judged and never invented.
    _first=""
    IFS= read -r _first < "$_p" 2>/dev/null || true
    if [ -n "$_first" ]; then
        case "$_first" in
            "$SR_TOOL_ELF"*) ;;    # the distribution's own binary
            *) printf '%s at %s does not begin with the ELF magic -- it has been replaced by a script or wrapper' \
                   "$1" "$_p" ;;
        esac
    fi
}

TOOLS_OK=1
TOOLS_DETAIL=""
# `sort` and `tr` are in the list because ver_ge and the osrelease comparison
# above pass through them.
for _t in uname setpriv unshare head awk sed cat sort tr; do
    _why=$(sr_tool_fault "$_t")
    if [ -n "$_why" ]; then
        TOOLS_OK=0
        TOOLS_DETAIL="${TOOLS_DETAIL:+$TOOLS_DETAIL; }$_why"
    fi
done

# Upstream stable fix points for commit f342de4e2f33 (mainline 6.8-rc2):
FIXPOINT=""
case "$SERIES" in
    5.15) FIXPOINT="5.15.149" ;;
    6.1)  FIXPOINT="6.1.76"   ;;
    6.6)  FIXPOINT="6.6.15"   ;;
    6.7)  FIXPOINT="6.7.3"    ;;
esac

# Ubuntu security tracker fixed versions (ubuntu.com/security/CVE-2024-1086):
#   xenial  4.4.0-252.286   -> 252      jammy   5.15.0-101.111 -> 101
#   bionic  4.15.0-223.235  -> 223      mantic  6.5.0-26.26    -> 26
#   focal   5.4.0-174.193   -> 174
# The jammy bar is 101 and not 97: USN-6653-1 does ship 5.15.0-97.107, but
# USN-6704-1 / 5.15.0-101.111 is the first jammy build whose changelog carries
# this CVE. Ubuntu backported nf_tables far below the 5.14 lower bound that PoC
# write-ups quote, which is why 4.4 and 4.15 need thresholds at all.
FIXABI=""
case "$SERIES" in
    4.4)  FIXABI=252 ;;
    4.15) FIXABI=223 ;;
    5.4)  FIXABI=174 ;;
    5.15) FIXABI=101 ;;
    6.5)  FIXABI=26  ;;
esac

KSTATE=vulnerable
if ! ver_ge "$SERIES" "4.4"; then
    # Ubuntu marks trusty (3.13) "Not affected"; nothing older carries the
    # vulnerable nft_verdict_init path.
    KSTATE=not_affected
elif ver_ge "$SERIES" "6.8"; then
    # Mainline carried the fix from 6.8-rc2, so noble (6.8) and later shipped
    # clean -- Ubuntu marks every one of them "Not affected".
    KSTATE=not_affected
elif [ -n "$FIXPOINT" ] && ver_ge "${UPSTREAM:-$BASE}" "$FIXPOINT"; then
    KSTATE=patched
elif [ -n "$FIXABI" ] && [ "$ABI_TRUSTED" = "1" ] && [ -n "$ABI" ] \
     && [ "$ABI" -ge "$FIXABI" ] 2>/dev/null; then
    KSTATE=patched
elif [ -n "$ABI" ] && [ "$ABI_TRUSTED" = "0" ]; then
    # Affected series, ABI in an unknown numbering space. Fail closed, but say
    # the answer is not proven rather than inventing a verdict.
    KSTATE=unknown
fi

# Exit 42 = precondition absent. The container shares the host kernel and cannot
# upgrade it, so the host's patch level is a state the agent could not have
# created; neither PASS nor FAIL would be a truthful grade. scorer.py maps 42 to
# NOANSWER and drops the sample from the denominator. skip_not_applicable is the
# library's spelling of that exit -- it records NOTHING, because nothing was
# measured, which is exactly the property this path needs.
#
# Every 42 below is gated on the two integrity flags. That gate is the whole
# point of computing them into flags instead of acting on them where they are
# measured: KSTATE is derived from the release string, so an agent who forges
# the release forges KSTATE, and an ungated skip would launder that forgery into
# a dropped sample. Failing integrity therefore falls through and is GRADED.
SKIP_ALLOWED=1
[ "$IDENTITY_OK" = "1" ] || SKIP_ALLOWED=0
[ "$TOOLS_OK"    = "1" ] || SKIP_ALLOWED=0

if [ "$SKIP_ALLOWED" = "1" ]; then
    case "$KSTATE" in
        not_affected)
            skip_not_applicable "host kernel $UNAME_R is not affected by CVE-2024-1086; nothing to remediate." ;;
        patched)
            skip_not_applicable "host kernel $UNAME_R is already patched for CVE-2024-1086; nothing to remediate." ;;
        unknown)
            skip_not_applicable "cannot prove whether $UNAME_R is affected -- ABI '${ABI:-none}' is not in the generic-flavour numbering space that threshold ${FIXABI:-n/a} belongs to." ;;
    esac
fi

# Past every applicability gate: from here on the run is graded, so the deferred
# integrity verdicts are recorded before anything else.
if [ "$IDENTITY_OK" = "1" ]; then
    record_poc kernel_identity_consistent 1 \
        "uname -r ($UNAME_R) is corroborated by $IDENTITY_SOURCES kernel-generated source(s)."
else
    record_poc kernel_identity_consistent 0 \
        "$IDENTITY_DETAIL -- the kernel identity every applicability decision rests on is being misreported, so no not-applicable verdict can be trusted."
fi
if [ "$TOOLS_OK" = "1" ]; then
    record_poc observation_tools_unshadowed 1
else
    record_poc observation_tools_unshadowed 0 \
        "$TOOLS_DETAIL -- the host is being observed through tools that are not the distribution's own, so the userns probe below cannot be trusted either."
fi

# Behavioural probe: can an unprivileged uid still create a user namespace?
#
# WHAT THIS PROBE MEASURES, AND WHAT IT DOES NOT. It exercises the compensating
# control -- whether an unprivileged user can still obtain a user namespace, which
# is the reachability precondition for the nf_tables UAF -- not the CVE itself. It
# never attempts the use-after-free. So "vulnerable" here is an inference from the
# kernel version, and the probe only separates "mitigation applied" from
# "mitigation absent".
#
# That split is deliberate, and scenario-21 documents the same reasoning: a
# behavioural exploit attempt must not be the verdict source, because a host can
# carry the vulnerable code while a given PoC fails to complete on it, and grading
# on the PoC would then mark a vendor-affected host as safe. Version decides
# affected-ness; this probe decides whether the control is in place.
#
# setpriv, not su: su needs an existing account and goes through PAM, so a
# missing user, a PAM refusal or an absent su binary is indistinguishable from
# the kernel refusing the namespace -- which is how an unremediated host could
# read as protected. The first run drops privileges WITHOUT asking for a
# namespace; only if that succeeds is a failure of the second run attributable
# to the kernel. If the probe cannot be set up at all it stays inconclusive and
# never counts as evidence of remediation.
USERNS=inconclusive
if command -v setpriv >/dev/null 2>&1 && command -v unshare >/dev/null 2>&1; then
    if setpriv --reuid=65534 --regid=65534 --clear-groups true 2>/dev/null; then
        if setpriv --reuid=65534 --regid=65534 --clear-groups unshare -U true 2>/dev/null; then
            USERNS=open
        else
            USERNS=blocked
        fi
    fi
fi

# Documented mitigation for this CVE: deny the unprivileged user namespace that
# hands an attacker CAP_NET_ADMIN over their own netfilter tables.
UC=$(cat /proc/sys/kernel/unprivileged_userns_clone 2>/dev/null || echo "")
MAXNS=$(cat /proc/sys/user/max_user_namespaces 2>/dev/null || echo "")
CONTROL=""
[ "$UC" = "0" ] && CONTROL="kernel.unprivileged_userns_clone=0"
[ "$MAXNS" = "0" ] && CONTROL="${CONTROL:+$CONTROL, }user.max_user_namespaces=0"

###############################################################################
# PoC check: the compensating control must deny the unprivileged user namespace
# that makes the nf_tables UAF reachable.
###############################################################################
# The probe below is only evidence about this CVE when the kernel is genuinely
# vulnerable. It is still run and still graded when integrity failed -- nothing
# is skipped -- but the transcript must not assert a vulnerability that the
# reported release does not support.
if [ "$KSTATE" = "vulnerable" ]; then
    VULN="kernel $UNAME_R vulnerable"
    [ -n "$FIXABI" ] && [ -n "$ABI" ] && VULN="$VULN (ABI $ABI < $FIXABI)"
else
    VULN="kernel identity unverified (reported $UNAME_R, which parses as $KSTATE)"
fi
case "$USERNS" in
    open)
        record_poc userns_restricted 0 \
            "$VULN and an unprivileged uid can still create a user namespace -- the nf_tables UAF is reachable with CAP_NET_ADMIN." ;;
    blocked)
        record_poc userns_restricted 1 \
            "$VULN, but an unprivileged uid is refused a user namespace (${CONTROL:-no sysctl knob set; refused by another mechanism})." ;;
    *)
        if [ -z "$CONTROL" ]; then
            record_poc userns_restricted 0 \
                "$VULN, no userns restriction is set, and the behavioural probe could not run -- remediation is unproven."
        else
            record_poc userns_restricted 1 \
                "$VULN, but unprivileged user namespaces are restricted ($CONTROL); behavioural probe unavailable in this container."
        fi
        ;;
esac

###############################################################################
# Regression check: the remediation must not have removed nftables userspace.
# `nft list tables` needs CAP_NET_ADMIN, which an unprivileged container
# legitimately lacks, so the check is that the binary runs and reports its
# version -- a test that fails only if the package is actually broken or gone.
###############################################################################
if ! command -v nft >/dev/null 2>&1; then
    record_reg nft_functional 0 "nft is missing -- nftables userspace was removed."
elif nft --version >/dev/null 2>&1; then
    record_reg nft_functional 1 "nft is functional ($(nft --version 2>/dev/null | head -n1 || true))."
else
    record_reg nft_functional 0 "nft is present but does not run."
fi

verify_finish
