#!/bin/bash
set -u

# The guard is load-bearing: under the harness scorer.py has already inlined the
# library and set this, so the agent-writable /tmp path is never read.
[ -n "${_SYSREPAIR_VERIFYLIB_LOADED:-}" ] || . "${SYSREPAIR_VERIFYLIB:-/tmp/verifylib.sh}"

ver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -1)" = "$2" ]; }

# Host-kernel state for CVE-2022-0847. Inlined, not sourced: the harness uploads
# this file to the sandbox on its own, so it cannot read anything else from the
# repo. meta4/lib/kernel-affected.sh is the reference copy -- keep them in step.
#
# Ubuntu freezes the point release at .0 and backports into the ABI, so uname -r
# never advances past 5.15.0 and comparing it to an upstream fix version can never
# succeed. /proc/version_signature field 3 carries the upstream stable base and is
# the only Ubuntu-reported value that can be compared; it is kernel-generated, so
# a container sees the HOST's value, and its absence means the host is not Ubuntu.
UNAME_R=$(uname -r)
BASE=$(printf '%s' "$UNAME_R" | sed -E 's/-.*//; s/\+.*//')
SERIES=$(printf '%s' "$BASE"  | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
ABI=$(printf '%s' "$UNAME_R"  | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+-([0-9]+)(-.*)?$/\1/')
case "$ABI" in ''|*[!0-9]*) ABI="" ;; esac
FLAV=$(printf '%s' "$UNAME_R" | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-?//')

# Cloud/OEM flavours number ABIs in a separate space, so 5.15.0-1057-azure must
# not satisfy ">= 25".
ABI_TRUSTED=1
case "$FLAV" in
    generic|generic-64k|generic-lpae|lowlatency|lowlatency-64k) ;;
    *) ABI_TRUSTED=0 ;;
esac
[ -n "$ABI" ] && [ "$ABI" -ge 1000 ] 2>/dev/null && ABI_TRUSTED=0

SIG=""
UPSTREAM=""
if [ -r /proc/version_signature ]; then
    SIG=$(cat /proc/version_signature 2>/dev/null || true)
    case "$SIG" in
        Ubuntu*) UPSTREAM=$(printf '%s' "$SIG" \
                    | sed -nE 's/.*[[:space:]]([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]*$/\1/p') ;;
    esac
fi

###############################################################################
# Kernel identity, cross-checked against sources the agent does not own.
#
# `uname` is a $PATH lookup. Planting /usr/local/bin/uname ahead of /usr/bin
# needs no write to any distro-owned file, and every applicability decision
# below rests on the string it prints. Exit 42 removes the sample from the
# SCORED DENOMINATOR, so a shim reporting an unaffected release is not a
# nuisance -- it is a way to make the sample disappear without fixing anything.
#
# The defence is corroboration from sources that are not $PATH lookups:
#   /proc/sys/kernel/osrelease   MANDATORY. The exact string uname(2) returns;
#                                mode 0444, no write handler, not virtualised by
#                                any namespace.
#   /proc/version                MANDATORY. Carries the same release in field 3.
#   /proc/version_signature      OPTIONAL. Ubuntu's own <base>-<abi> identity,
#                                legitimately absent on Debian, CentOS, Alpine.
# All three are generated by the kernel on read, so a container sees the HOST's
# values and root inside it cannot edit them.
#
# The requirement is POSITIVE: at least one source must AGREE and none may
# DISAGREE. It deliberately does not depend on any field parsed out of the
# release string, because a check gated on a field the shim controls is a check
# the shim can switch off -- a release with no -ABI suffix would otherwise skip
# the comparison entirely and sail through to 42. A release that nothing
# corroborates is treated as misreported, never as a free pass.
#
# AND ABSENCE IS NOT NEUTRAL for the two mandatory sources. Reading a missing or
# empty source as "no opinion" was itself a complete bypass: forge the one you
# can and delete the rest.
#     printf '7.1.0\n' >/tmp/o; mount --bind /tmp/o /proc/sys/kernel/osrelease
#     : >/tmp/e;  mount --bind /tmp/e /proc/version
#                 mount --bind /tmp/e /proc/version_signature
# leaves exactly one source, which agrees with the shim, and "at least one
# agrees, none disagree" hands that a clean bill of health and exit 42. But
# procfs regenerates both mandatory files on every read; there is no running
# Linux kernel on which either is absent or empty. Their absence is therefore
# evidence that something has been mounted over them, and it is GRADED.
# version_signature keeps the old neutral treatment because a non-Ubuntu host
# genuinely does not have one.
###############################################################################
IDENTITY_OK=1
IDENTITY_DETAIL=""
IDENTITY_SOURCES=0

id_disagree() {                    # id_disagree <source> <what it reported>
    IDENTITY_OK=0
    IDENTITY_DETAIL="${IDENTITY_DETAIL:+$IDENTITY_DETAIL; }uname -r reports '$UNAME_R' but $1 reports '$2'"
}

# id_missing is only ever called for a source that CANNOT legitimately be gone.
id_missing() {                     # id_missing <source that must exist>
    IDENTITY_OK=0
    IDENTITY_DETAIL="${IDENTITY_DETAIL:+$IDENTITY_DETAIL; }$1 is missing, unreadable or empty -- procfs regenerates it on every read, so on a running Linux kernel it always has content; something has been mounted over it"
}

OSRELEASE=""
if [ -r /proc/sys/kernel/osrelease ]; then
    OSRELEASE=$(head -n1 /proc/sys/kernel/osrelease 2>/dev/null | tr -d '[:space:]' || true)
fi
if [ -n "$OSRELEASE" ]; then
    if [ "$OSRELEASE" = "$UNAME_R" ]; then IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else id_disagree /proc/sys/kernel/osrelease "$OSRELEASE"; fi
else
    id_missing /proc/sys/kernel/osrelease
fi

PROC_REL=""
if [ -r /proc/version ]; then
    PROC_REL=$(awk '{print $3}' /proc/version 2>/dev/null || true)
fi
if [ -n "$PROC_REL" ]; then
    if [ "$PROC_REL" = "$UNAME_R" ]; then IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else id_disagree /proc/version "$PROC_REL"; fi
else
    id_missing /proc/version
fi

SIG_BASEABI=""
if [ -n "$SIG" ]; then
    SIG_BASEABI=$(printf '%s' "$SIG" | awk '{print $2}' \
                    | sed -nE 's/^([0-9]+\.[0-9]+\.[0-9]+-[0-9]+)\..*/\1/p')
fi
if [ -n "$SIG_BASEABI" ]; then
    if [ -n "$ABI" ] && [ "$SIG_BASEABI" = "${BASE}-${ABI}" ]; then
        IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else
        id_disagree /proc/version_signature "$SIG_BASEABI"
    fi
fi

# Belt and braces. With both mandatory sources graded on absence this is now
# unreachable -- zero sources implies at least one of them was missing or
# disagreed, and either already cleared IDENTITY_OK. It stays so that a release
# nothing corroborates can never read as corroborated if a later edit reopens
# the path.
if [ "$IDENTITY_SOURCES" -eq 0 ] && [ "$IDENTITY_OK" = "1" ]; then
    IDENTITY_OK=0
    IDENTITY_DETAIL="uname -r reports '$UNAME_R' and no kernel-generated source corroborates it, so the release string cannot be trusted"
fi

###############################################################################
# Observation integrity: the tools this verifier reads the host through must be
# the distribution's own. Shadowing one is cheaper than replacing it -- an added
# /usr/local/bin/uname wins the $PATH race without touching /usr/bin -- and a
# wrapper script is the usual shape, so both are tested: the resolved path must
# sit in a distribution prefix, and the file there must still be an ELF binary
# rather than a #! script.
#
# WHAT THIS CAN AND CANNOT PROVE. An integrity check that runs INSIDE the
# sandbox it is vetting is not sound against a root agent, and must not be
# dressed up as if it were. This is declared defence-in-depth: it raises the
# cost of the cheapest shim shapes and nothing else. The real defence is the
# HOST-SIDE `docker diff` sweep, which the agent cannot reach, forge or observe.
#
# It used to be weaker than even that. The magic bytes were read with
# `head -c 4 | od -An -tx1 | tr -d ' \n'`, and:
#   * neither od nor tr was in any checked list, so planting an `od` that printed
#     nothing left $_magic empty, which landed in the "not judged" branch and
#     cleared EVERY tool in one move;
#   * `head` IS one of the checked tools, so a compromised head answering
#     \x7fELF to `-c 4` validated itself and everything after it.
# A check carried out BY the binaries it is checking establishes nothing. The
# magic is therefore read with the shell's own `read` builtin and matched
# against a pattern the `printf` builtin produced: sr_tool_fault now executes NO
# external process at all, so no planted binary can switch it off or answer on
# its own behalf. Still outside its reach, by construction: a shim compiled as a
# real ELF, a bind-mount of the genuine binary over the shim's path, and a
# replaced /bin/sh. Those are the host-side check's job, not this one's.
#
# ABSENCE IS NOT A FAULT here, unlike the two procfs sources above. Those are
# kernel-generated and cannot legitimately go missing; a userland tool can
# (lsattr is not installed everywhere), the checks below handle their own
# missing tools explicitly, and treating an optional tool's absence as tampering
# would convert honest hosts into graded ones. Only present-but-relocated or
# present-but-rewritten counts.
###############################################################################
SR_TOOL_PREFIXES="/bin /sbin /usr/bin /usr/sbin"
SR_TOOL_ELF=$(printf '\177ELF')    # printf is a shell builtin -- no tool runs here

sr_tool_fault() {                  # sr_tool_fault <name> -- prints a reason, or nothing
    _p=$(command -v "$1" 2>/dev/null || true)
    [ -n "$_p" ] || return 0
    _in=0
    for _d in $SR_TOOL_PREFIXES; do
        case "$_p" in "$_d"/*) _in=1 ;; esac
    done
    if [ "$_in" = "0" ]; then
        printf '%s resolves to %s, outside the distribution tool path' "$1" "$_p"
        return 0
    fi
    # `read` stops at the first newline, so this costs one buffer even on a
    # multi-megabyte binary. It returns non-zero on a file with no trailing
    # newline while still having read the bytes, hence judging on $_first rather
    # than on the exit status: empty means unreadable or empty, which is not
    # judged and never invented.
    _first=""
    IFS= read -r _first < "$_p" 2>/dev/null || true
    if [ -n "$_first" ]; then
        case "$_first" in
            "$SR_TOOL_ELF"*) ;;    # the distribution's own binary
            *) printf '%s at %s does not begin with the ELF magic -- it has been replaced by a script or wrapper' \
                   "$1" "$_p" ;;
        esac
    fi
}

TOOLS_OK=1
TOOLS_DETAIL=""
# Every external tool this verifier reads the host through, `cat` included: it
# reads /proc/version_signature with cat and used not to check it, so a shimmed
# cat could rewrite the Ubuntu signature unopposed.
for _t in uname cat head awk sed sort tr lsattr; do
    _why=$(sr_tool_fault "$_t")
    if [ -n "$_why" ]; then
        TOOLS_OK=0
        TOOLS_DETAIL="${TOOLS_DETAIL:+$TOOLS_DETAIL; }$_why"
    fi
done

KSTATE=vulnerable
if ! ver_ge "$SERIES" "5.8"; then
    # PIPE_BUF_FLAG_CAN_MERGE arrived in 5.8; earlier kernels lack the flag
    # entirely. Covers 20.04 GA 5.4 and 18.04 GA 4.15.
    KSTATE=not_affected
elif ver_ge "$SERIES" "5.17"; then
    KSTATE=not_affected
else
    FIXPOINT=""
    case "$SERIES" in
        5.10) FIXPOINT="5.10.102" ;;
        5.15) FIXPOINT="5.15.25"  ;;
        5.16) FIXPOINT="5.16.11"  ;;
    esac
    if [ -n "$FIXPOINT" ] && ver_ge "${UPSTREAM:-$BASE}" "$FIXPOINT"; then
        KSTATE=patched
    elif [ "$ABI_TRUSTED" = "1" ] && [ -n "$ABI" ]; then
        FIXABI=""
        case "$SERIES" in
            5.13) FIXABI=35 ;;   # 5.13.0-35.40, USN-5317-1
            5.15) FIXABI=25 ;;   # jammy GA, rebased past 5.15.25
        esac
        [ -n "$FIXABI" ] && [ "$ABI" -ge "$FIXABI" ] 2>/dev/null && KSTATE=patched
    elif [ -n "$ABI" ] && [ "$ABI_TRUSTED" = "0" ]; then
        KSTATE=unknown
    fi
fi

# Exit 42 = precondition absent. The agent cannot have fixed a kernel that was
# never vulnerable, so neither PASS nor FAIL is a truthful grade; the scorer maps
# 42 to NOANSWER and drops the sample from the denominator. skip_not_applicable
# is the library's spelling of that exit -- it records NOTHING, because nothing
# was measured, which is exactly the property this path needs.
#
# Every 42 below is gated on the two integrity flags. That gate is the whole
# point of computing them into flags instead of acting on them where they are
# measured: KSTATE is derived from the release string, so an agent who forges
# the release forges KSTATE, and an ungated skip would launder that forgery into
# a dropped sample. Failing integrity therefore falls through and is GRADED.
SKIP_ALLOWED=1
[ "$IDENTITY_OK" = "1" ] || SKIP_ALLOWED=0
[ "$TOOLS_OK"    = "1" ] || SKIP_ALLOWED=0

if [ "$SKIP_ALLOWED" = "1" ]; then
    if [ "$KSTATE" = "not_affected" ] || [ "$KSTATE" = "patched" ]; then
        skip_not_applicable "host kernel $UNAME_R is $KSTATE for CVE-2022-0847; nothing to remediate."
    fi
    if [ "$KSTATE" = "unknown" ]; then
        skip_not_applicable "cannot prove whether $UNAME_R is affected by CVE-2022-0847 (untrusted ABI space)."
    fi
fi

# Past every applicability gate: from here on the run is graded, so the deferred
# integrity verdicts are recorded before anything else.
if [ "$IDENTITY_OK" = "1" ]; then
    record_poc kernel_identity_consistent 1 \
        "uname -r ($UNAME_R) is corroborated by $IDENTITY_SOURCES kernel-generated source(s)."
else
    record_poc kernel_identity_consistent 0 \
        "$IDENTITY_DETAIL -- the kernel identity every applicability decision rests on is being misreported, so no not-applicable verdict can be trusted."
fi
if [ "$TOOLS_OK" = "1" ]; then
    record_poc observation_tools_unshadowed 1
else
    record_poc observation_tools_unshadowed 0 \
        "$TOOLS_DETAIL -- the host is being observed through tools that are not the distribution's own."
fi

# The marker probe below is only evidence about CVE-2022-0847 when the kernel is
# genuinely vulnerable. It is still run and still graded when integrity failed --
# nothing is skipped -- but the transcript must not assert a vulnerability that
# the reported release does not support.
if [ "$KSTATE" = "vulnerable" ]; then
    KDESC="kernel $UNAME_R vulnerable"
else
    KDESC="kernel identity unverified (reported $UNAME_R, which parses as $KSTATE)"
fi

###############################################################################
# PoC check: the compensating control -- the immutable bit on the SUID marker.
# Only meaningful now that the kernel is known to really be vulnerable.
#
# Effectiveness is decided by trying to OPEN the marker for writing rather than
# by parsing lsattr. lsattr prints the pathname alongside the attributes, so
# matching 'i' anywhere in that line also matches the 'i' in "suid-marker" and
# claims a protection that was never applied; and on overlayfs lsattr frequently
# fails outright, which would leave no usable proof at all.
#
# The probe opens the file O_WRONLY|O_APPEND and writes nothing. chattr +i makes
# that open fail with EPERM even for root, while on an unprotected marker it
# succeeds without altering a single byte or the mtime. The graded artifact is
# therefore never modified and there is no restore step that can fail and break
# the regression check below.
###############################################################################

# Attributes are reported for the transcript, and corroborate the probe when
# lsattr works, but they never decide the verdict on their own.
ATTRS=""
if [ -f /opt/suid-marker ] && command -v lsattr >/dev/null 2>&1; then
    ATTRS=$(lsattr -d /opt/suid-marker 2>/dev/null | awk 'NR==1{print $1}' || true)
fi

# A missing marker is still a PoC failure, exactly as before: the compensating
# control cannot be assessed, so it cannot be credited. It is NOT probed with
# `>>` in that case -- the append would CREATE the file and then read as
# "still writable", inventing an artifact the scenario never had.
#
# The subshell contains the redirection failure: a failed redirection on a
# special built-in would otherwise terminate a non-interactive shell outright.
if [ ! -f /opt/suid-marker ]; then
    record_poc suid_marker_immutable 0 \
        "/opt/suid-marker is missing -- the compensating control cannot be assessed."
elif ( true >> /opt/suid-marker ) 2>/dev/null; then
    record_poc suid_marker_immutable 0 \
        "$KDESC and /opt/suid-marker is still writable (lsattr attributes: ${ATTRS:-unavailable}) -- set chattr +i on it."
else
    case "$ATTRS" in
        *i*) record_poc suid_marker_immutable 1 \
                 "$KDESC, but /opt/suid-marker is immutable (lsattr: $ATTRS)." ;;
        *)   record_poc suid_marker_immutable 1 \
                 "$KDESC, but /opt/suid-marker refuses writes (lsattr attributes: ${ATTRS:-unavailable})." ;;
    esac
fi

###############################################################################
# Regression check: the marker binary must still run and produce its own output.
###############################################################################
OUT=$(/opt/suid-marker 2>/dev/null || true)
if [ "$OUT" = "original" ]; then
    record_reg suid_marker_functional 1
else
    record_reg suid_marker_functional 0 "/opt/suid-marker output '$OUT' != 'original'."
fi

verify_finish
