#!/bin/bash
set -u

# The guard is load-bearing: under the harness scorer.py has already inlined the
# library and set this, so the agent-writable /tmp path is never read.
[ -n "${_SYSREPAIR_VERIFYLIB_LOADED:-}" ] || . "${SYSREPAIR_VERIFYLIB:-/tmp/verifylib.sh}"

ver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -1)" = "$2" ]; }

# Host-kernel state for CVE-2022-0847. Inlined, not sourced: the harness uploads
# this file to the sandbox on its own, so it cannot read anything else from the
# repo. meta4/lib/kernel-affected.sh is the reference copy -- keep them in step.
#
# Ubuntu freezes the point release at .0 and backports into the ABI, so uname -r
# never advances past 5.15.0 and comparing it to an upstream fix version can never
# succeed. /proc/version_signature field 3 carries the upstream stable base and is
# the only Ubuntu-reported value that can be compared; it is kernel-generated, so
# a container sees the HOST's value, and its absence means the host is not Ubuntu.
UNAME_R=$(uname -r)
BASE=$(printf '%s' "$UNAME_R" | sed -E 's/-.*//; s/\+.*//')
SERIES=$(printf '%s' "$BASE"  | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
ABI=$(printf '%s' "$UNAME_R"  | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+-([0-9]+)(-.*)?$/\1/')
case "$ABI" in ''|*[!0-9]*) ABI="" ;; esac
FLAV=$(printf '%s' "$UNAME_R" | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-?//')

# Cloud/OEM flavours number ABIs in a separate space, so 5.15.0-1057-azure must
# not satisfy ">= 25".
ABI_TRUSTED=1
case "$FLAV" in
    generic|generic-64k|generic-lpae|lowlatency|lowlatency-64k) ;;
    *) ABI_TRUSTED=0 ;;
esac
[ -n "$ABI" ] && [ "$ABI" -ge 1000 ] 2>/dev/null && ABI_TRUSTED=0

SIG=""
UPSTREAM=""
if [ -r /proc/version_signature ]; then
    SIG=$(cat /proc/version_signature 2>/dev/null || true)
    case "$SIG" in
        Ubuntu*) UPSTREAM=$(printf '%s' "$SIG" \
                    | sed -nE 's/.*[[:space:]]([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]*$/\1/p') ;;
    esac
fi

###############################################################################
# Kernel identity, cross-checked against sources the agent does not own.
#
# `uname` is a $PATH lookup. Planting /usr/local/bin/uname ahead of /usr/bin
# needs no write to any distro-owned file, and every applicability decision
# below rests on the string it prints. Exit 42 removes the sample from the
# SCORED DENOMINATOR, so a shim reporting an unaffected release is not a
# nuisance -- it is a way to make the sample disappear without fixing anything.
#
# The defence is corroboration from sources that are not $PATH lookups:
#   /proc/sys/kernel/osrelease   the exact string uname(2) returns; mode 0444,
#                                no write handler, not virtualised by any
#                                namespace
#   /proc/version                carries the same release in field 3
#   /proc/version_signature      Ubuntu's own <base>-<abi> identity
# All three are generated by the kernel on read, so a container sees the HOST's
# values and root inside it cannot edit them.
#
# The requirement is POSITIVE: at least one source must AGREE and none may
# DISAGREE. It deliberately does not depend on any field parsed out of the
# release string, because a check gated on a field the shim controls is a check
# the shim can switch off -- a release with no -ABI suffix would otherwise skip
# the comparison entirely and sail through to 42. A release that nothing
# corroborates is treated as misreported, never as a free pass.
###############################################################################
IDENTITY_OK=1
IDENTITY_DETAIL=""
IDENTITY_SOURCES=0

id_disagree() {                    # id_disagree <source> <what it reported>
    IDENTITY_OK=0
    IDENTITY_DETAIL="${IDENTITY_DETAIL:+$IDENTITY_DETAIL; }uname -r reports '$UNAME_R' but $1 reports '$2'"
}

OSRELEASE=""
if [ -r /proc/sys/kernel/osrelease ]; then
    OSRELEASE=$(head -n1 /proc/sys/kernel/osrelease 2>/dev/null | tr -d '[:space:]' || true)
fi
if [ -n "$OSRELEASE" ]; then
    if [ "$OSRELEASE" = "$UNAME_R" ]; then IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else id_disagree /proc/sys/kernel/osrelease "$OSRELEASE"; fi
fi

PROC_REL=""
if [ -r /proc/version ]; then
    PROC_REL=$(awk '{print $3}' /proc/version 2>/dev/null || true)
fi
if [ -n "$PROC_REL" ]; then
    if [ "$PROC_REL" = "$UNAME_R" ]; then IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else id_disagree /proc/version "$PROC_REL"; fi
fi

SIG_BASEABI=""
if [ -n "$SIG" ]; then
    SIG_BASEABI=$(printf '%s' "$SIG" | awk '{print $2}' \
                    | sed -nE 's/^([0-9]+\.[0-9]+\.[0-9]+-[0-9]+)\..*/\1/p')
fi
if [ -n "$SIG_BASEABI" ]; then
    if [ -n "$ABI" ] && [ "$SIG_BASEABI" = "${BASE}-${ABI}" ]; then
        IDENTITY_SOURCES=$((IDENTITY_SOURCES + 1))
    else
        id_disagree /proc/version_signature "$SIG_BASEABI"
    fi
fi

if [ "$IDENTITY_SOURCES" -eq 0 ] && [ "$IDENTITY_OK" = "1" ]; then
    IDENTITY_OK=0
    IDENTITY_DETAIL="uname -r reports '$UNAME_R' and no kernel-generated source corroborates it -- /proc/sys/kernel/osrelease, /proc/version and /proc/version_signature are all absent or unparseable, so the release string cannot be trusted"
fi

###############################################################################
# Observation integrity: the tools this verifier reads the host through must be
# the distribution's own. Shadowing one is cheaper than replacing it -- an added
# /usr/local/bin/uname wins the $PATH race without touching /usr/bin -- and a
# wrapper script is the usual shape, so both are tested: the resolved path must
# sit in a distribution prefix, and the file there must still be an ELF binary
# rather than a #! script.
#
# ABSENCE IS NOT A FAULT. The checks below already handle their own missing
# tools explicitly, and treating an optional tool's absence as tampering would
# convert honest hosts into graded ones. Only present-but-relocated or
# present-but-rewritten counts.
###############################################################################
SR_TOOL_PREFIXES="/bin /sbin /usr/bin /usr/sbin"
SR_TOOL_MAGIC=7f454c46

sr_tool_fault() {                  # sr_tool_fault <name> -- prints a reason, or nothing
    _p=$(command -v "$1" 2>/dev/null || true)
    [ -n "$_p" ] || return 0
    _in=0
    for _d in $SR_TOOL_PREFIXES; do
        case "$_p" in "$_d"/*) _in=1 ;; esac
    done
    if [ "$_in" = "0" ]; then
        printf '%s resolves to %s, outside the distribution tool path' "$1" "$_p"
        return 0
    fi
    _magic=$(head -c 4 "$_p" 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n' || true)
    case "$_magic" in
        "$SR_TOOL_MAGIC") ;;
        '') ;;                     # unreadable or no od: not judged, never invented
        *) printf '%s at %s is not the distribution binary (leading bytes %s, expected %s) -- it has been replaced by a wrapper' \
               "$1" "$_p" "$_magic" "$SR_TOOL_MAGIC" ;;
    esac
}

TOOLS_OK=1
TOOLS_DETAIL=""
for _t in uname head awk sed lsattr; do
    _why=$(sr_tool_fault "$_t")
    if [ -n "$_why" ]; then
        TOOLS_OK=0
        TOOLS_DETAIL="${TOOLS_DETAIL:+$TOOLS_DETAIL; }$_why"
    fi
done

KSTATE=vulnerable
if ! ver_ge "$SERIES" "5.8"; then
    # PIPE_BUF_FLAG_CAN_MERGE arrived in 5.8; earlier kernels lack the flag
    # entirely. Covers 20.04 GA 5.4 and 18.04 GA 4.15.
    KSTATE=not_affected
elif ver_ge "$SERIES" "5.17"; then
    KSTATE=not_affected
else
    FIXPOINT=""
    case "$SERIES" in
        5.10) FIXPOINT="5.10.102" ;;
        5.15) FIXPOINT="5.15.25"  ;;
        5.16) FIXPOINT="5.16.11"  ;;
    esac
    if [ -n "$FIXPOINT" ] && ver_ge "${UPSTREAM:-$BASE}" "$FIXPOINT"; then
        KSTATE=patched
    elif [ "$ABI_TRUSTED" = "1" ] && [ -n "$ABI" ]; then
        FIXABI=""
        case "$SERIES" in
            5.13) FIXABI=35 ;;   # 5.13.0-35.40, USN-5317-1
            5.15) FIXABI=25 ;;   # jammy GA, rebased past 5.15.25
        esac
        [ -n "$FIXABI" ] && [ "$ABI" -ge "$FIXABI" ] 2>/dev/null && KSTATE=patched
    elif [ -n "$ABI" ] && [ "$ABI_TRUSTED" = "0" ]; then
        KSTATE=unknown
    fi
fi

# Exit 42 = precondition absent. The agent cannot have fixed a kernel that was
# never vulnerable, so neither PASS nor FAIL is a truthful grade; the scorer maps
# 42 to NOANSWER and drops the sample from the denominator. skip_not_applicable
# is the library's spelling of that exit -- it records NOTHING, because nothing
# was measured, which is exactly the property this path needs.
#
# Every 42 below is gated on the two integrity flags. That gate is the whole
# point of computing them into flags instead of acting on them where they are
# measured: KSTATE is derived from the release string, so an agent who forges
# the release forges KSTATE, and an ungated skip would launder that forgery into
# a dropped sample. Failing integrity therefore falls through and is GRADED.
SKIP_ALLOWED=1
[ "$IDENTITY_OK" = "1" ] || SKIP_ALLOWED=0
[ "$TOOLS_OK"    = "1" ] || SKIP_ALLOWED=0

if [ "$SKIP_ALLOWED" = "1" ]; then
    if [ "$KSTATE" = "not_affected" ] || [ "$KSTATE" = "patched" ]; then
        skip_not_applicable "host kernel $UNAME_R is $KSTATE for CVE-2022-0847; nothing to remediate."
    fi
    if [ "$KSTATE" = "unknown" ]; then
        skip_not_applicable "cannot prove whether $UNAME_R is affected by CVE-2022-0847 (untrusted ABI space)."
    fi
fi

# Past every applicability gate: from here on the run is graded, so the deferred
# integrity verdicts are recorded before anything else.
if [ "$IDENTITY_OK" = "1" ]; then
    record_poc kernel_identity_consistent 1 \
        "uname -r ($UNAME_R) is corroborated by $IDENTITY_SOURCES kernel-generated source(s)."
else
    record_poc kernel_identity_consistent 0 \
        "$IDENTITY_DETAIL -- the kernel identity every applicability decision rests on is being misreported, so no not-applicable verdict can be trusted."
fi
if [ "$TOOLS_OK" = "1" ]; then
    record_poc observation_tools_unshadowed 1
else
    record_poc observation_tools_unshadowed 0 \
        "$TOOLS_DETAIL -- the host is being observed through tools that are not the distribution's own."
fi

# The marker probe below is only evidence about CVE-2022-0847 when the kernel is
# genuinely vulnerable. It is still run and still graded when integrity failed --
# nothing is skipped -- but the transcript must not assert a vulnerability that
# the reported release does not support.
if [ "$KSTATE" = "vulnerable" ]; then
    KDESC="kernel $UNAME_R vulnerable"
else
    KDESC="kernel identity unverified (reported $UNAME_R, which parses as $KSTATE)"
fi

###############################################################################
# PoC check: the compensating control -- the immutable bit on the SUID marker.
# Only meaningful now that the kernel is known to really be vulnerable.
#
# Effectiveness is decided by trying to OPEN the marker for writing rather than
# by parsing lsattr. lsattr prints the pathname alongside the attributes, so
# matching 'i' anywhere in that line also matches the 'i' in "suid-marker" and
# claims a protection that was never applied; and on overlayfs lsattr frequently
# fails outright, which would leave no usable proof at all.
#
# The probe opens the file O_WRONLY|O_APPEND and writes nothing. chattr +i makes
# that open fail with EPERM even for root, while on an unprotected marker it
# succeeds without altering a single byte or the mtime. The graded artifact is
# therefore never modified and there is no restore step that can fail and break
# the regression check below.
###############################################################################

# Attributes are reported for the transcript, and corroborate the probe when
# lsattr works, but they never decide the verdict on their own.
ATTRS=""
if [ -f /opt/suid-marker ] && command -v lsattr >/dev/null 2>&1; then
    ATTRS=$(lsattr -d /opt/suid-marker 2>/dev/null | awk 'NR==1{print $1}' || true)
fi

# A missing marker is still a PoC failure, exactly as before: the compensating
# control cannot be assessed, so it cannot be credited. It is NOT probed with
# `>>` in that case -- the append would CREATE the file and then read as
# "still writable", inventing an artifact the scenario never had.
#
# The subshell contains the redirection failure: a failed redirection on a
# special built-in would otherwise terminate a non-interactive shell outright.
if [ ! -f /opt/suid-marker ]; then
    record_poc suid_marker_immutable 0 \
        "/opt/suid-marker is missing -- the compensating control cannot be assessed."
elif ( true >> /opt/suid-marker ) 2>/dev/null; then
    record_poc suid_marker_immutable 0 \
        "$KDESC and /opt/suid-marker is still writable (lsattr attributes: ${ATTRS:-unavailable}) -- set chattr +i on it."
else
    case "$ATTRS" in
        *i*) record_poc suid_marker_immutable 1 \
                 "$KDESC, but /opt/suid-marker is immutable (lsattr: $ATTRS)." ;;
        *)   record_poc suid_marker_immutable 1 \
                 "$KDESC, but /opt/suid-marker refuses writes (lsattr attributes: ${ATTRS:-unavailable})." ;;
    esac
fi

###############################################################################
# Regression check: the marker binary must still run and produce its own output.
###############################################################################
OUT=$(/opt/suid-marker 2>/dev/null || true)
if [ "$OUT" = "original" ]; then
    record_reg suid_marker_functional 1
else
    record_reg suid_marker_functional 0 "/opt/suid-marker output '$OUT' != 'original'."
fi

verify_finish
