FROM tleemcjr/metasploitable2@sha256:e559450b37dccc1909eafa2df5b20bb052e1bd801246f4539a3ef183d5f7288a

# Metasploitable 2 has Samba configured with wide links = yes

COPY verify.sh /verify.sh
CMD ["/bin/services.sh"]
