[libdefaults]
    default_realm = CORP.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = true

[realms]
    CORP.LOCAL = {
        kdc = corp-dc01.corp.local
        admin_server = corp-dc01.corp.local
    }

[domain_realm]
    .corp.local = CORP.LOCAL
    corp.local  = CORP.LOCAL
